server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/x-library?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zzl10250523
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 127.0.0.1
    port: 6379
    connect-timeout: 10000
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto